# my copyparty conf

[global]
  p: 8080
  e2dsa
  e2ts
  df: 1G
  no-robots
  rproxy: -1
  xff-src: lan
  usernames
  shr: /share
  shr-who: auth
  vague-403
  no-reload
  exp
  grid
  dothidden

% /srv/copyparty-account.conf
